### PR TITLE
Create base project structure

### LINKED ISSUE #1: Create blank Front end
Create vite React App template

### LINKED ISSUE #9: Add .gitignore

### LINKED ISSUE #10: Add Spring API
Added 4 dependencies
1. Spring Web WEB
Build web, including RESTful, applications using Spring MVC. Uses Apache Tomcat as the default embedded container.
2. Validation I/O
Bean Validation with Hibernate validator.
3. Spring Data JPA SQL
Persist data in SQL stores with Java Persistence API using Spring Data and Hibernate.
4. MS SQL Server Driver 
A JDBC and R2DBC driver that provides access to Microsoft SQL Server and Azure SQL Database from any Java application.

### LINKED ISSUE #11: Create vite react template
npm create@vitelatest

### PR DESCRIPTION
**Pull request by shellywilliamsreichert802**

### CODE REVIEW

**Review by shellywilliamsreichert802 — COMMENTED** [review]
Once someone reviews it should show in git main branch. Thanks!

**Review by koolkat254 — COMMENTED** [review]
To confirm, this is TypeScript. I like typescript, but make sure everyone knows and agrees... :)

**Comment by shellywilliamsreichert802** [comment]
Thank you for the feed back! I’ll check in with my group. Enjoy your trip!

Best,

*Shelly Reichert*

***@***.***

(802) 598-3038

**Comment by shellywilliamsreichert802** [comment]
Changed from typescript to javascript. Waiting on team to discuss preference

**Comment by shellywilliamsreichert802** [comment]
Add .gitignore
Created React App template
Add Spring API with dependencies
Is Javascript okay with team? We can use this or delete and restart if team prefers. Once someone reviews it should show in git main branch. Thanks!

**Pull request closed without merging**
